Added `.env.example`
ghoshRitesh12/aniwatch-api pull request #25
Opened 2024-02-28 12:43 UTC by ayushch80

2024-02-28 15:08 UTC, ghoshRitesh12 requested changes

2024-02-28 15:08 UTC, ghoshRitesh12 commented on src/utils/constants.ts
> +const DOMAIN = process.env.DOMAIN || 'aniwatchtv.to'
Everything is good, just add double quotes for the fallback domain :)

2024-02-28 15:57 UTC, ayushch80 commented on src/utils/constants.ts
> +const DOMAIN = process.env.DOMAIN || 'aniwatchtv.to'
done

2024-02-28 18:24 UTC, merged

2024-03-18 16:49 UTC, ghoshRitesh12 reviewed
lgtm